# The west manifest file for Zephyr based ABC board.

manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: ABC-fw
      url-base: https://github.com/ChrisGammell
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v2.0.0
      import: true
